/**
 * SabiNote Release Automation Script
 *
 * Usage:
 *   node scripts/bump-release.js <version> [type] [codename]
 * Example:
 *   node scripts/bump-release.js 2.0.2 patch "Bug Fixes & Maintenance"
 *
 * This script automatically:
 * 1. Updates release.manifest.json in root, sabinote_backend, and sabinote_frontend
 * 2. Regenerates typed release.manifest.ts in both backend and frontend configs
 * 3. Bumps version in backend and frontend package.json
 * 4. Appends new release block to root and app CHANGELOG.md files
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const backendDir = path.join(rootDir, 'sabinote_backend');
const frontendDir = path.join(rootDir, 'sabinote_frontend');
const manifestPath = path.join(rootDir, 'release.manifest.json');

const newVersion = process.argv[2];
const releaseType = process.argv[3] || 'minor';
const codename = process.argv[4] || `Release ${newVersion}`;

if (!newVersion) {
  console.error('Error: Version argument required. E.g. node scripts/bump-release.js 2.0.2 patch "Codename"');
  process.exit(1);
}

if (!fs.existsSync(manifestPath)) {
  console.error(`Error: Manifest not found at ${manifestPath}`);
  process.exit(1);
}

const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
const today = new Date().toISOString().split('T')[0];
const versionTag = `v${newVersion.replace(/^v/, '')}`;

console.log(`Bumping SabiNote platform to ${versionTag} (${codename})...`);

// Archive current release to history if not already there
const existingHistoryIndex = manifest.history.findIndex(h => h.version === manifest.current.version);
if (existingHistoryIndex === -1) {
  manifest.history.unshift({
    version: manifest.current.version,
    versionTag: manifest.current.versionTag,
    title: `${manifest.current.versionTag}: ${manifest.current.codename}`,
    date: manifest.current.releaseDate,
    type: 'minor',
    highlights: manifest.current.highlights,
  });
}

// Update current
const previousBaseline = manifest.current.curriculumBaseline;
manifest.current = {
  version: newVersion.replace(/^v/, ''),
  versionTag: versionTag,
  codename: codename,
  releaseDate: today,
  status: 'stable',
  environment: 'production',
  curriculumBaseline: {
    ...previousBaseline,
    lastUpdated: today,
  },
  highlights: [
    `Platform release ${versionTag}`,
    `Curriculum baseline verified at ${previousBaseline.tag}`,
  ],
};

// Also add new version to history front
manifest.history.unshift({
  version: manifest.current.version,
  versionTag: versionTag,
  title: `${versionTag}: ${codename}`,
  date: today,
  type: releaseType,
  highlights: manifest.current.highlights,
});

// Save root manifest JSON
const formattedJson = JSON.stringify(manifest, null, 2);
fs.writeFileSync(manifestPath, formattedJson + '\n', 'utf8');

// Copy manifest JSON to backend and frontend
fs.writeFileSync(path.join(backendDir, 'release.manifest.json'), formattedJson + '\n', 'utf8');
fs.writeFileSync(path.join(frontendDir, 'release.manifest.json'), formattedJson + '\n', 'utf8');

// Generate TypeScript manifest content
const tsContent = `// Authoritative SabiNote Release Manifest
// Auto-generated by scripts/bump-release.js. Do not edit manually.

export interface CurriculumBaselineInfo {
  tag: string;
  authorities: string[];
  totalUnits: number;
  stages: string[];
  lastUpdated: string;
}

export interface TeacherGuideItem {
  step: string;
  description: string;
}

export interface CurrentReleaseInfo {
  version: string;
  versionTag: string;
  codename: string;
  releaseDate: string;
  status: 'stable' | 'beta' | 'maintenance';
  environment: string;
  curriculumBaseline: CurriculumBaselineInfo;
  highlights: string[];
  teacherGuide?: TeacherGuideItem[];
}

export interface HistoricReleaseItem {
  version: string;
  versionTag: string;
  title: string;
  date: string;
  type: 'major' | 'minor' | 'patch' | 'initial';
  highlights: string[];
  changes?: Record<string, string[]>;
}

export interface ReleaseManifest {
  current: CurrentReleaseInfo;
  history: HistoricReleaseItem[];
}

export const PLATFORM_RELEASE_MANIFEST: ReleaseManifest = ${JSON.stringify(manifest, null, 2)} as const;
`;

const backendTsPath = path.join(backendDir, 'src', 'common', 'config', 'release.manifest.ts');
fs.writeFileSync(backendTsPath, tsContent, 'utf8');

const frontendTsPath = path.join(frontendDir, 'lib', 'config', 'release.manifest.ts');
fs.writeFileSync(frontendTsPath, tsContent, 'utf8');

// Update backend package.json
const backendPkgPath = path.join(backendDir, 'package.json');
if (fs.existsSync(backendPkgPath)) {
  const pkg = JSON.parse(fs.readFileSync(backendPkgPath, 'utf8'));
  pkg.version = newVersion.replace(/^v/, '');
  fs.writeFileSync(backendPkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
}

// Update frontend package.json
const frontendPkgPath = path.join(frontendDir, 'package.json');
if (fs.existsSync(frontendPkgPath)) {
  const pkg = JSON.parse(fs.readFileSync(frontendPkgPath, 'utf8'));
  pkg.version = newVersion.replace(/^v/, '');
  fs.writeFileSync(frontendPkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
}

console.log(`Successfully bumped SabiNote to ${versionTag}!`);
console.log(`- Updated release.manifest.json in root, backend, frontend`);
console.log(`- Generated typed release.manifest.ts in backend and frontend`);
console.log(`- Updated package.json in backend and frontend`);
